// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: protos/cards_runner.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Port struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          *structpb.Value        `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Port) Reset() {
	*x = Port{}
	mi := &file_protos_cards_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cards_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Port.ProtoReflect.Descriptor instead.
func (*Port) Descriptor() ([]byte, []int) {
	return file_protos_cards_runner_proto_rawDescGZIP(), []int{0}
}

func (x *Port) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Port) GetType() *structpb.Value {
	if x != nil {
		return x.Type
	}
	return nil
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	In            map[string]*Port       `protobuf:"bytes,2,rep,name=in,proto3" json:"in,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Out           map[string]*Port       `protobuf:"bytes,3,rep,name=out,proto3" json:"out,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_protos_cards_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cards_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_protos_cards_runner_proto_rawDescGZIP(), []int{1}
}

func (x *Card) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Card) GetIn() map[string]*Port {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *Card) GetOut() map[string]*Port {
	if x != nil {
		return x.Out
	}
	return nil
}

type Cards struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cards) Reset() {
	*x = Cards{}
	mi := &file_protos_cards_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cards) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cards) ProtoMessage() {}

func (x *Cards) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cards_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cards.ProtoReflect.Descriptor instead.
func (*Cards) Descriptor() ([]byte, []int) {
	return file_protos_cards_runner_proto_rawDescGZIP(), []int{2}
}

func (x *Cards) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type EmptyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReq) Reset() {
	*x = EmptyReq{}
	mi := &file_protos_cards_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReq) ProtoMessage() {}

func (x *EmptyReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cards_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReq.ProtoReflect.Descriptor instead.
func (*EmptyReq) Descriptor() ([]byte, []int) {
	return file_protos_cards_runner_proto_rawDescGZIP(), []int{3}
}

type CardInputWithCardName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          string                 `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	Input         map[string]*Port       `protobuf:"bytes,2,rep,name=input,proto3" json:"input,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Output        map[string]*Port       `protobuf:"bytes,3,rep,name=output,proto3" json:"output,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardInputWithCardName) Reset() {
	*x = CardInputWithCardName{}
	mi := &file_protos_cards_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardInputWithCardName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardInputWithCardName) ProtoMessage() {}

func (x *CardInputWithCardName) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cards_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardInputWithCardName.ProtoReflect.Descriptor instead.
func (*CardInputWithCardName) Descriptor() ([]byte, []int) {
	return file_protos_cards_runner_proto_rawDescGZIP(), []int{4}
}

func (x *CardInputWithCardName) GetCard() string {
	if x != nil {
		return x.Card
	}
	return ""
}

func (x *CardInputWithCardName) GetInput() map[string]*Port {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *CardInputWithCardName) GetOutput() map[string]*Port {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_protos_cards_runner_proto protoreflect.FileDescriptor

const file_protos_cards_runner_proto_rawDesc = "" +
	"\n" +
	"\x19protos/cards_runner.proto\x12\apipeman\x1a\x1cgoogle/protobuf/struct.proto\"F\n" +
	"\x04Port\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x04type\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x04type\"\xf8\x01\n" +
	"\x04Card\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x02in\x18\x02 \x03(\v2\x15.pipeman.Card.InEntryR\x02in\x12(\n" +
	"\x03out\x18\x03 \x03(\v2\x16.pipeman.Card.OutEntryR\x03out\x1aD\n" +
	"\aInEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.pipeman.PortR\x05value:\x028\x01\x1aE\n" +
	"\bOutEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.pipeman.PortR\x05value:\x028\x01\",\n" +
	"\x05Cards\x12#\n" +
	"\x05cards\x18\x01 \x03(\v2\r.pipeman.CardR\x05cards\"\n" +
	"\n" +
	"\bEmptyReq\"\xc3\x02\n" +
	"\x15CardInputWithCardName\x12\x12\n" +
	"\x04card\x18\x01 \x01(\tR\x04card\x12?\n" +
	"\x05input\x18\x02 \x03(\v2).pipeman.CardInputWithCardName.InputEntryR\x05input\x12B\n" +
	"\x06output\x18\x03 \x03(\v2*.pipeman.CardInputWithCardName.OutputEntryR\x06output\x1aG\n" +
	"\n" +
	"InputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.pipeman.PortR\x05value:\x028\x01\x1aH\n" +
	"\vOutputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.pipeman.PortR\x05value:\x028\x012\x89\x01\n" +
	"\vCardsRunner\x126\n" +
	"\x11GetSupportedCards\x12\x11.pipeman.EmptyReq\x1a\x0e.pipeman.Cards\x12B\n" +
	"\aRunCard\x12\x1e.pipeman.CardInputWithCardName\x1a\x17.google.protobuf.StructB(Z&github.com/ondbyte/pm/protos/go/protosb\x06proto3"

var (
	file_protos_cards_runner_proto_rawDescOnce sync.Once
	file_protos_cards_runner_proto_rawDescData []byte
)

func file_protos_cards_runner_proto_rawDescGZIP() []byte {
	file_protos_cards_runner_proto_rawDescOnce.Do(func() {
		file_protos_cards_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_cards_runner_proto_rawDesc), len(file_protos_cards_runner_proto_rawDesc)))
	})
	return file_protos_cards_runner_proto_rawDescData
}

var file_protos_cards_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protos_cards_runner_proto_goTypes = []any{
	(*Port)(nil),                  // 0: pipeman.Port
	(*Card)(nil),                  // 1: pipeman.Card
	(*Cards)(nil),                 // 2: pipeman.Cards
	(*EmptyReq)(nil),              // 3: pipeman.EmptyReq
	(*CardInputWithCardName)(nil), // 4: pipeman.CardInputWithCardName
	nil,                           // 5: pipeman.Card.InEntry
	nil,                           // 6: pipeman.Card.OutEntry
	nil,                           // 7: pipeman.CardInputWithCardName.InputEntry
	nil,                           // 8: pipeman.CardInputWithCardName.OutputEntry
	(*structpb.Value)(nil),        // 9: google.protobuf.Value
	(*structpb.Struct)(nil),       // 10: google.protobuf.Struct
}
var file_protos_cards_runner_proto_depIdxs = []int32{
	9,  // 0: pipeman.Port.type:type_name -> google.protobuf.Value
	5,  // 1: pipeman.Card.in:type_name -> pipeman.Card.InEntry
	6,  // 2: pipeman.Card.out:type_name -> pipeman.Card.OutEntry
	1,  // 3: pipeman.Cards.cards:type_name -> pipeman.Card
	7,  // 4: pipeman.CardInputWithCardName.input:type_name -> pipeman.CardInputWithCardName.InputEntry
	8,  // 5: pipeman.CardInputWithCardName.output:type_name -> pipeman.CardInputWithCardName.OutputEntry
	0,  // 6: pipeman.Card.InEntry.value:type_name -> pipeman.Port
	0,  // 7: pipeman.Card.OutEntry.value:type_name -> pipeman.Port
	0,  // 8: pipeman.CardInputWithCardName.InputEntry.value:type_name -> pipeman.Port
	0,  // 9: pipeman.CardInputWithCardName.OutputEntry.value:type_name -> pipeman.Port
	3,  // 10: pipeman.CardsRunner.GetSupportedCards:input_type -> pipeman.EmptyReq
	4,  // 11: pipeman.CardsRunner.RunCard:input_type -> pipeman.CardInputWithCardName
	2,  // 12: pipeman.CardsRunner.GetSupportedCards:output_type -> pipeman.Cards
	10, // 13: pipeman.CardsRunner.RunCard:output_type -> google.protobuf.Struct
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_protos_cards_runner_proto_init() }
func file_protos_cards_runner_proto_init() {
	if File_protos_cards_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_cards_runner_proto_rawDesc), len(file_protos_cards_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_cards_runner_proto_goTypes,
		DependencyIndexes: file_protos_cards_runner_proto_depIdxs,
		MessageInfos:      file_protos_cards_runner_proto_msgTypes,
	}.Build()
	File_protos_cards_runner_proto = out.File
	file_protos_cards_runner_proto_goTypes = nil
	file_protos_cards_runner_proto_depIdxs = nil
}
