// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: protos/cards_runner.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Struct, Value } from "../google/protobuf/struct";

export const protobufPackage = "pipeman";

export interface Port {
  name: string;
  type: any | undefined;
}

export interface Card {
  name: string;
  in: { [key: string]: Port };
  out: { [key: string]: Port };
}

export interface Card_InEntry {
  key: string;
  value: Port | undefined;
}

export interface Card_OutEntry {
  key: string;
  value: Port | undefined;
}

export interface Cards {
  cards: Card[];
}

export interface EmptyReq {
}

export interface CardInputWithCardName {
  card: string;
  input: { [key: string]: Port };
  output: { [key: string]: Port };
}

export interface CardInputWithCardName_InputEntry {
  key: string;
  value: Port | undefined;
}

export interface CardInputWithCardName_OutputEntry {
  key: string;
  value: Port | undefined;
}

function createBasePort(): Port {
  return { name: "", type: undefined };
}

export const Port: MessageFns<Port> = {
  encode(message: Port, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.type !== undefined) {
      Value.encode(Value.wrap(message.type), writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Port {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePort();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.type = Value.unwrap(Value.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Port {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      type: isSet(object?.type) ? object.type : undefined,
    };
  },

  toJSON(message: Port): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.type !== undefined) {
      obj.type = message.type;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Port>, I>>(base?: I): Port {
    return Port.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Port>, I>>(object: I): Port {
    const message = createBasePort();
    message.name = object.name ?? "";
    message.type = object.type ?? undefined;
    return message;
  },
};

function createBaseCard(): Card {
  return { name: "", in: {}, out: {} };
}

export const Card: MessageFns<Card> = {
  encode(message: Card, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    Object.entries(message.in).forEach(([key, value]) => {
      Card_InEntry.encode({ key: key as any, value }, writer.uint32(18).fork()).join();
    });
    Object.entries(message.out).forEach(([key, value]) => {
      Card_OutEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Card {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCard();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const entry2 = Card_InEntry.decode(reader, reader.uint32());
          if (entry2.value !== undefined) {
            message.in[entry2.key] = entry2.value;
          }
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = Card_OutEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.out[entry3.key] = entry3.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Card {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      in: isObject(object.in)
        ? Object.entries(object.in).reduce<{ [key: string]: Port }>((acc, [key, value]) => {
          acc[key] = Port.fromJSON(value);
          return acc;
        }, {})
        : {},
      out: isObject(object.out)
        ? Object.entries(object.out).reduce<{ [key: string]: Port }>((acc, [key, value]) => {
          acc[key] = Port.fromJSON(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: Card): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.in) {
      const entries = Object.entries(message.in);
      if (entries.length > 0) {
        obj.in = {};
        entries.forEach(([k, v]) => {
          obj.in[k] = Port.toJSON(v);
        });
      }
    }
    if (message.out) {
      const entries = Object.entries(message.out);
      if (entries.length > 0) {
        obj.out = {};
        entries.forEach(([k, v]) => {
          obj.out[k] = Port.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Card>, I>>(base?: I): Card {
    return Card.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Card>, I>>(object: I): Card {
    const message = createBaseCard();
    message.name = object.name ?? "";
    message.in = Object.entries(object.in ?? {}).reduce<{ [key: string]: Port }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = Port.fromPartial(value);
      }
      return acc;
    }, {});
    message.out = Object.entries(object.out ?? {}).reduce<{ [key: string]: Port }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = Port.fromPartial(value);
      }
      return acc;
    }, {});
    return message;
  },
};

function createBaseCard_InEntry(): Card_InEntry {
  return { key: "", value: undefined };
}

export const Card_InEntry: MessageFns<Card_InEntry> = {
  encode(message: Card_InEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      Port.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Card_InEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCard_InEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = Port.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Card_InEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? Port.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: Card_InEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = Port.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Card_InEntry>, I>>(base?: I): Card_InEntry {
    return Card_InEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Card_InEntry>, I>>(object: I): Card_InEntry {
    const message = createBaseCard_InEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null) ? Port.fromPartial(object.value) : undefined;
    return message;
  },
};

function createBaseCard_OutEntry(): Card_OutEntry {
  return { key: "", value: undefined };
}

export const Card_OutEntry: MessageFns<Card_OutEntry> = {
  encode(message: Card_OutEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      Port.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Card_OutEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCard_OutEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = Port.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Card_OutEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? Port.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: Card_OutEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = Port.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Card_OutEntry>, I>>(base?: I): Card_OutEntry {
    return Card_OutEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Card_OutEntry>, I>>(object: I): Card_OutEntry {
    const message = createBaseCard_OutEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null) ? Port.fromPartial(object.value) : undefined;
    return message;
  },
};

function createBaseCards(): Cards {
  return { cards: [] };
}

export const Cards: MessageFns<Cards> = {
  encode(message: Cards, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.cards) {
      Card.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Cards {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCards();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cards.push(Card.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Cards {
    return { cards: globalThis.Array.isArray(object?.cards) ? object.cards.map((e: any) => Card.fromJSON(e)) : [] };
  },

  toJSON(message: Cards): unknown {
    const obj: any = {};
    if (message.cards?.length) {
      obj.cards = message.cards.map((e) => Card.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Cards>, I>>(base?: I): Cards {
    return Cards.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Cards>, I>>(object: I): Cards {
    const message = createBaseCards();
    message.cards = object.cards?.map((e) => Card.fromPartial(e)) || [];
    return message;
  },
};

function createBaseEmptyReq(): EmptyReq {
  return {};
}

export const EmptyReq: MessageFns<EmptyReq> = {
  encode(_: EmptyReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmptyReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmptyReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): EmptyReq {
    return {};
  },

  toJSON(_: EmptyReq): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<EmptyReq>, I>>(base?: I): EmptyReq {
    return EmptyReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmptyReq>, I>>(_: I): EmptyReq {
    const message = createBaseEmptyReq();
    return message;
  },
};

function createBaseCardInputWithCardName(): CardInputWithCardName {
  return { card: "", input: {}, output: {} };
}

export const CardInputWithCardName: MessageFns<CardInputWithCardName> = {
  encode(message: CardInputWithCardName, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.card !== "") {
      writer.uint32(10).string(message.card);
    }
    Object.entries(message.input).forEach(([key, value]) => {
      CardInputWithCardName_InputEntry.encode({ key: key as any, value }, writer.uint32(18).fork()).join();
    });
    Object.entries(message.output).forEach(([key, value]) => {
      CardInputWithCardName_OutputEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CardInputWithCardName {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCardInputWithCardName();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.card = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const entry2 = CardInputWithCardName_InputEntry.decode(reader, reader.uint32());
          if (entry2.value !== undefined) {
            message.input[entry2.key] = entry2.value;
          }
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = CardInputWithCardName_OutputEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.output[entry3.key] = entry3.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CardInputWithCardName {
    return {
      card: isSet(object.card) ? globalThis.String(object.card) : "",
      input: isObject(object.input)
        ? Object.entries(object.input).reduce<{ [key: string]: Port }>((acc, [key, value]) => {
          acc[key] = Port.fromJSON(value);
          return acc;
        }, {})
        : {},
      output: isObject(object.output)
        ? Object.entries(object.output).reduce<{ [key: string]: Port }>((acc, [key, value]) => {
          acc[key] = Port.fromJSON(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: CardInputWithCardName): unknown {
    const obj: any = {};
    if (message.card !== "") {
      obj.card = message.card;
    }
    if (message.input) {
      const entries = Object.entries(message.input);
      if (entries.length > 0) {
        obj.input = {};
        entries.forEach(([k, v]) => {
          obj.input[k] = Port.toJSON(v);
        });
      }
    }
    if (message.output) {
      const entries = Object.entries(message.output);
      if (entries.length > 0) {
        obj.output = {};
        entries.forEach(([k, v]) => {
          obj.output[k] = Port.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CardInputWithCardName>, I>>(base?: I): CardInputWithCardName {
    return CardInputWithCardName.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CardInputWithCardName>, I>>(object: I): CardInputWithCardName {
    const message = createBaseCardInputWithCardName();
    message.card = object.card ?? "";
    message.input = Object.entries(object.input ?? {}).reduce<{ [key: string]: Port }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = Port.fromPartial(value);
      }
      return acc;
    }, {});
    message.output = Object.entries(object.output ?? {}).reduce<{ [key: string]: Port }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = Port.fromPartial(value);
      }
      return acc;
    }, {});
    return message;
  },
};

function createBaseCardInputWithCardName_InputEntry(): CardInputWithCardName_InputEntry {
  return { key: "", value: undefined };
}

export const CardInputWithCardName_InputEntry: MessageFns<CardInputWithCardName_InputEntry> = {
  encode(message: CardInputWithCardName_InputEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      Port.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CardInputWithCardName_InputEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCardInputWithCardName_InputEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = Port.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CardInputWithCardName_InputEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? Port.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: CardInputWithCardName_InputEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = Port.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CardInputWithCardName_InputEntry>, I>>(
    base?: I,
  ): CardInputWithCardName_InputEntry {
    return CardInputWithCardName_InputEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CardInputWithCardName_InputEntry>, I>>(
    object: I,
  ): CardInputWithCardName_InputEntry {
    const message = createBaseCardInputWithCardName_InputEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null) ? Port.fromPartial(object.value) : undefined;
    return message;
  },
};

function createBaseCardInputWithCardName_OutputEntry(): CardInputWithCardName_OutputEntry {
  return { key: "", value: undefined };
}

export const CardInputWithCardName_OutputEntry: MessageFns<CardInputWithCardName_OutputEntry> = {
  encode(message: CardInputWithCardName_OutputEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      Port.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CardInputWithCardName_OutputEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCardInputWithCardName_OutputEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = Port.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CardInputWithCardName_OutputEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? Port.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: CardInputWithCardName_OutputEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = Port.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CardInputWithCardName_OutputEntry>, I>>(
    base?: I,
  ): CardInputWithCardName_OutputEntry {
    return CardInputWithCardName_OutputEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CardInputWithCardName_OutputEntry>, I>>(
    object: I,
  ): CardInputWithCardName_OutputEntry {
    const message = createBaseCardInputWithCardName_OutputEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null) ? Port.fromPartial(object.value) : undefined;
    return message;
  },
};

export interface CardsRunner {
  GetSupportedCards(request: EmptyReq): Promise<Cards>;
  RunCard(request: CardInputWithCardName): Promise<Struct>;
}

export const CardsRunnerServiceName = "pipeman.CardsRunner";
export class CardsRunnerClientImpl implements CardsRunner {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || CardsRunnerServiceName;
    this.rpc = rpc;
    this.GetSupportedCards = this.GetSupportedCards.bind(this);
    this.RunCard = this.RunCard.bind(this);
  }
  GetSupportedCards(request: EmptyReq): Promise<Cards> {
    const data = EmptyReq.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetSupportedCards", data);
    return promise.then((data) => Cards.decode(new BinaryReader(data)));
  }

  RunCard(request: CardInputWithCardName): Promise<Struct> {
    const data = CardInputWithCardName.encode(request).finish();
    const promise = this.rpc.request(this.service, "RunCard", data);
    return promise.then((data) => Struct.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
